on:
  workflow_call:
    inputs:
      threshold-low:
        type: number
        required: false
        default: 50
      threshold-high:
        type: number
        required: false
        default: 80
jobs:
  check-coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Generate coverage report
        uses: sergiy-decima/clover-coverage-action@1.0.0
        with:
          filename: coverage/clover.xml
          threshold: ${{ inputs.threshold-low }} ${{ inputs.threshold-high }}
      - name: Fail below threshold
        uses: themichaelhall/check-code-coverage@v2
        with:
          report: coverage/clover.xml
          required-percentage: ${{ inputs.threshold-low }}
